name: cd

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/cd.yml"
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages # need ${{ secrets.NUGET_TOKEN }}
      NUGET_PACKAGE_SOURCE: https://api.nuget.org/v3/index.json # https://apiint.nugettest.org/v3/index.json

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - run: dotnet restore --locked-mode

      - id: meta
        shell: bash
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo version=${tag#v} | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore -p:Version=${{ steps.meta.outputs.version }} -p:RepositoryBranch=$(git rev-parse --abbrev-ref HEAD) -p:RepositoryCommit=$(git rev-parse HEAD)
          mv ./src/**/bin/Release/*nupkg ./

      - name: Publish the package to nuget.org
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.NUGET_PACKAGE_SOURCE }}

      - uses: softprops/action-gh-release@v1
        if: ${{ steps.meta.outputs.is_release == 'true' }}
        with:
          tag_name: ${{ steps.meta.outputs.tag }}